### PR TITLE
Close the stream when when the background is clicked.

### PR DESCRIPTION
**Pull request by tomlister**
Hey mate.

Haven't tested this, as I used GitHub's latest and greatest in-browser coding interface (press . on any repository).
Give me a shout if it works or if it doesn't.

Cheers.

### CODE REVIEW

**Comment by king-millez** [comment]
Awesome. Can you quickly merge the latest commit I did on `overhaul-1` into your branch, then I'll test.

**Comment by king-millez** [comment]
So it works - sort of.

The VideoJS container sits on top of the background and extends for most of the width of the screen:
image

Clicking below and above it does work though!

**Comment by tomlister** [comment]
Could you reduce the width or no?

**Comment by king-millez** [comment]
Possibly, the width is assigned with VideoJS, so it could be overridden by some CSS I assume. Do you wanna try it?

**Comment by tomlister** [comment]
I'll investigate.

**Pull request closed without merging**
